/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MonitorImport } from './routes/monitor'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as TradingIndexImport } from './routes/trading/index'
import { Route as StrategiesIndexImport } from './routes/strategies/index'
import { Route as BacktestsIndexImport } from './routes/backtests/index'
import { Route as TradingAnalyticsImport } from './routes/trading/analytics'
import { Route as TradingAccountsImport } from './routes/trading/accounts'
import { Route as StrategiesSimpleImport } from './routes/strategies/simple'
import { Route as StrategiesCompareImport } from './routes/strategies/compare'
import { Route as StrategiesAdvancedImport } from './routes/strategies/advanced'
import { Route as StrategiesIdImport } from './routes/strategies/$id'
import { Route as BacktestsIdImport } from './routes/backtests/$id'
import { Route as AuthVerifyEmailImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthResendVerificationImport } from './routes/auth/resend-verification'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'

// Create/Update Routes

const MonitorRoute = MonitorImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TradingIndexRoute = TradingIndexImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRoute,
} as any)

const StrategiesIndexRoute = StrategiesIndexImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRoute,
} as any)

const BacktestsIndexRoute = BacktestsIndexImport.update({
  id: '/backtests/',
  path: '/backtests/',
  getParentRoute: () => rootRoute,
} as any)

const TradingAnalyticsRoute = TradingAnalyticsImport.update({
  id: '/trading/analytics',
  path: '/trading/analytics',
  getParentRoute: () => rootRoute,
} as any)

const TradingAccountsRoute = TradingAccountsImport.update({
  id: '/trading/accounts',
  path: '/trading/accounts',
  getParentRoute: () => rootRoute,
} as any)

const StrategiesSimpleRoute = StrategiesSimpleImport.update({
  id: '/strategies/simple',
  path: '/strategies/simple',
  getParentRoute: () => rootRoute,
} as any)

const StrategiesCompareRoute = StrategiesCompareImport.update({
  id: '/strategies/compare',
  path: '/strategies/compare',
  getParentRoute: () => rootRoute,
} as any)

const StrategiesAdvancedRoute = StrategiesAdvancedImport.update({
  id: '/strategies/advanced',
  path: '/strategies/advanced',
  getParentRoute: () => rootRoute,
} as any)

const StrategiesIdRoute = StrategiesIdImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => rootRoute,
} as any)

const BacktestsIdRoute = BacktestsIdImport.update({
  id: '/backtests/$id',
  path: '/backtests/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthResendVerificationRoute = AuthResendVerificationImport.update({
  id: '/auth/resend-verification',
  path: '/auth/resend-verification',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/resend-verification': {
      id: '/auth/resend-verification'
      path: '/auth/resend-verification'
      fullPath: '/auth/resend-verification'
      preLoaderRoute: typeof AuthResendVerificationImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/backtests/$id': {
      id: '/backtests/$id'
      path: '/backtests/$id'
      fullPath: '/backtests/$id'
      preLoaderRoute: typeof BacktestsIdImport
      parentRoute: typeof rootRoute
    }
    '/strategies/$id': {
      id: '/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof StrategiesIdImport
      parentRoute: typeof rootRoute
    }
    '/strategies/advanced': {
      id: '/strategies/advanced'
      path: '/strategies/advanced'
      fullPath: '/strategies/advanced'
      preLoaderRoute: typeof StrategiesAdvancedImport
      parentRoute: typeof rootRoute
    }
    '/strategies/compare': {
      id: '/strategies/compare'
      path: '/strategies/compare'
      fullPath: '/strategies/compare'
      preLoaderRoute: typeof StrategiesCompareImport
      parentRoute: typeof rootRoute
    }
    '/strategies/simple': {
      id: '/strategies/simple'
      path: '/strategies/simple'
      fullPath: '/strategies/simple'
      preLoaderRoute: typeof StrategiesSimpleImport
      parentRoute: typeof rootRoute
    }
    '/trading/accounts': {
      id: '/trading/accounts'
      path: '/trading/accounts'
      fullPath: '/trading/accounts'
      preLoaderRoute: typeof TradingAccountsImport
      parentRoute: typeof rootRoute
    }
    '/trading/analytics': {
      id: '/trading/analytics'
      path: '/trading/analytics'
      fullPath: '/trading/analytics'
      preLoaderRoute: typeof TradingAnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/backtests/': {
      id: '/backtests/'
      path: '/backtests'
      fullPath: '/backtests'
      preLoaderRoute: typeof BacktestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests': typeof BacktestsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/trading': typeof TradingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests': typeof BacktestsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/trading': typeof TradingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests/': typeof BacktestsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/trading/': typeof TradingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests'
    | '/strategies'
    | '/trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests'
    | '/strategies'
    | '/trading'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests/'
    | '/strategies/'
    | '/trading/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MonitorRoute: typeof MonitorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResendVerificationRoute: typeof AuthResendVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BacktestsIdRoute: typeof BacktestsIdRoute
  StrategiesIdRoute: typeof StrategiesIdRoute
  StrategiesAdvancedRoute: typeof StrategiesAdvancedRoute
  StrategiesCompareRoute: typeof StrategiesCompareRoute
  StrategiesSimpleRoute: typeof StrategiesSimpleRoute
  TradingAccountsRoute: typeof TradingAccountsRoute
  TradingAnalyticsRoute: typeof TradingAnalyticsRoute
  BacktestsIndexRoute: typeof BacktestsIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MonitorRoute: MonitorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResendVerificationRoute: AuthResendVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BacktestsIdRoute: BacktestsIdRoute,
  StrategiesIdRoute: StrategiesIdRoute,
  StrategiesAdvancedRoute: StrategiesAdvancedRoute,
  StrategiesCompareRoute: StrategiesCompareRoute,
  StrategiesSimpleRoute: StrategiesSimpleRoute,
  TradingAccountsRoute: TradingAccountsRoute,
  TradingAnalyticsRoute: TradingAnalyticsRoute,
  BacktestsIndexRoute: BacktestsIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/monitor",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/register",
        "/auth/resend-verification",
        "/auth/reset-password",
        "/auth/verify-email",
        "/backtests/$id",
        "/strategies/$id",
        "/strategies/advanced",
        "/strategies/compare",
        "/strategies/simple",
        "/trading/accounts",
        "/trading/analytics",
        "/backtests/",
        "/strategies/",
        "/trading/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/monitor": {
      "filePath": "monitor.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/resend-verification": {
      "filePath": "auth/resend-verification.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/verify-email": {
      "filePath": "auth/verify-email.tsx"
    },
    "/backtests/$id": {
      "filePath": "backtests/$id.tsx"
    },
    "/strategies/$id": {
      "filePath": "strategies/$id.tsx"
    },
    "/strategies/advanced": {
      "filePath": "strategies/advanced.tsx"
    },
    "/strategies/compare": {
      "filePath": "strategies/compare.tsx"
    },
    "/strategies/simple": {
      "filePath": "strategies/simple.tsx"
    },
    "/trading/accounts": {
      "filePath": "trading/accounts.tsx"
    },
    "/trading/analytics": {
      "filePath": "trading/analytics.tsx"
    },
    "/backtests/": {
      "filePath": "backtests/index.tsx"
    },
    "/strategies/": {
      "filePath": "strategies/index.tsx"
    },
    "/trading/": {
      "filePath": "trading/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
