/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradingIndexRouteImport } from './routes/trading/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BacktestsIndexRouteImport } from './routes/backtests/index'
import { Route as TradingAnalyticsRouteImport } from './routes/trading/analytics'
import { Route as TradingAccountsRouteImport } from './routes/trading/accounts'
import { Route as StrategiesSimpleRouteImport } from './routes/strategies/simple'
import { Route as StrategiesHealthRouteImport } from './routes/strategies/health'
import { Route as StrategiesCompareRouteImport } from './routes/strategies/compare'
import { Route as StrategiesAdvancedRouteImport } from './routes/strategies/advanced'
import { Route as StrategiesIdRouteImport } from './routes/strategies/$id'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as BacktestsIdRouteImport } from './routes/backtests/$id'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthResendVerificationRouteImport } from './routes/auth/resend-verification'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsIndexRoute = BacktestsIndexRouteImport.update({
  id: '/backtests/',
  path: '/backtests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingAnalyticsRoute = TradingAnalyticsRouteImport.update({
  id: '/trading/analytics',
  path: '/trading/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingAccountsRoute = TradingAccountsRouteImport.update({
  id: '/trading/accounts',
  path: '/trading/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesSimpleRoute = StrategiesSimpleRouteImport.update({
  id: '/strategies/simple',
  path: '/strategies/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesHealthRoute = StrategiesHealthRouteImport.update({
  id: '/strategies/health',
  path: '/strategies/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesCompareRoute = StrategiesCompareRouteImport.update({
  id: '/strategies/compare',
  path: '/strategies/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesAdvancedRoute = StrategiesAdvancedRouteImport.update({
  id: '/strategies/advanced',
  path: '/strategies/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIdRoute = StrategiesIdRouteImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsIdRoute = BacktestsIdRouteImport.update({
  id: '/backtests/$id',
  path: '/backtests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResendVerificationRoute = AuthResendVerificationRouteImport.update({
  id: '/auth/resend-verification',
  path: '/auth/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/health': typeof StrategiesHealthRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests/': typeof BacktestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/health': typeof StrategiesHealthRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests': typeof BacktestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/trading': typeof TradingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resend-verification': typeof AuthResendVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/backtests/$id': typeof BacktestsIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/advanced': typeof StrategiesAdvancedRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/strategies/health': typeof StrategiesHealthRoute
  '/strategies/simple': typeof StrategiesSimpleRoute
  '/trading/accounts': typeof TradingAccountsRoute
  '/trading/analytics': typeof TradingAnalyticsRoute
  '/backtests/': typeof BacktestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/settings/account'
    | '/settings/theme'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/health'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests/'
    | '/settings/'
    | '/strategies/'
    | '/trading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/settings/account'
    | '/settings/theme'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/health'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests'
    | '/settings'
    | '/strategies'
    | '/trading'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/monitor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resend-verification'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/backtests/$id'
    | '/settings/account'
    | '/settings/theme'
    | '/strategies/$id'
    | '/strategies/advanced'
    | '/strategies/compare'
    | '/strategies/health'
    | '/strategies/simple'
    | '/trading/accounts'
    | '/trading/analytics'
    | '/backtests/'
    | '/settings/'
    | '/strategies/'
    | '/trading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MonitorRoute: typeof MonitorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResendVerificationRoute: typeof AuthResendVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BacktestsIdRoute: typeof BacktestsIdRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  StrategiesIdRoute: typeof StrategiesIdRoute
  StrategiesAdvancedRoute: typeof StrategiesAdvancedRoute
  StrategiesCompareRoute: typeof StrategiesCompareRoute
  StrategiesHealthRoute: typeof StrategiesHealthRoute
  StrategiesSimpleRoute: typeof StrategiesSimpleRoute
  TradingAccountsRoute: typeof TradingAccountsRoute
  TradingAnalyticsRoute: typeof TradingAnalyticsRoute
  BacktestsIndexRoute: typeof BacktestsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests/': {
      id: '/backtests/'
      path: '/backtests'
      fullPath: '/backtests/'
      preLoaderRoute: typeof BacktestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/analytics': {
      id: '/trading/analytics'
      path: '/trading/analytics'
      fullPath: '/trading/analytics'
      preLoaderRoute: typeof TradingAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/accounts': {
      id: '/trading/accounts'
      path: '/trading/accounts'
      fullPath: '/trading/accounts'
      preLoaderRoute: typeof TradingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/simple': {
      id: '/strategies/simple'
      path: '/strategies/simple'
      fullPath: '/strategies/simple'
      preLoaderRoute: typeof StrategiesSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/health': {
      id: '/strategies/health'
      path: '/strategies/health'
      fullPath: '/strategies/health'
      preLoaderRoute: typeof StrategiesHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/compare': {
      id: '/strategies/compare'
      path: '/strategies/compare'
      fullPath: '/strategies/compare'
      preLoaderRoute: typeof StrategiesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/advanced': {
      id: '/strategies/advanced'
      path: '/strategies/advanced'
      fullPath: '/strategies/advanced'
      preLoaderRoute: typeof StrategiesAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$id': {
      id: '/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof StrategiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests/$id': {
      id: '/backtests/$id'
      path: '/backtests/$id'
      fullPath: '/backtests/$id'
      preLoaderRoute: typeof BacktestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resend-verification': {
      id: '/auth/resend-verification'
      path: '/auth/resend-verification'
      fullPath: '/auth/resend-verification'
      preLoaderRoute: typeof AuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MonitorRoute: MonitorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResendVerificationRoute: AuthResendVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BacktestsIdRoute: BacktestsIdRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  StrategiesIdRoute: StrategiesIdRoute,
  StrategiesAdvancedRoute: StrategiesAdvancedRoute,
  StrategiesCompareRoute: StrategiesCompareRoute,
  StrategiesHealthRoute: StrategiesHealthRoute,
  StrategiesSimpleRoute: StrategiesSimpleRoute,
  TradingAccountsRoute: TradingAccountsRoute,
  TradingAnalyticsRoute: TradingAnalyticsRoute,
  BacktestsIndexRoute: BacktestsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
