/**
 * Frontend API Client — 公开导出
 */

// 错误模型
export {
  type AppError,
  type AppErrorKind,
  httpStatusToKind,
  createAppError,
  networkError,
  timeoutError,
  isAuthError,
} from './errors'

// 信封解包
export {
  type SuccessEnvelope,
  type ErrorEnvelope,
  type PagedData,
  type Envelope,
  unwrapEnvelope,
  unwrapPagedEnvelope,
  isSuccessEnvelope,
  parseEnvelope,
} from './envelope'

// 请求核心
export {
  type ClientConfig,
  type RequestOptions,
  configureClient,
  getClientConfig,
  request,
  get,
  post,
  patch,
  put,
  del,
} from './request'

// Endpoints
export {
  type UserProfile,
  type LoginPayload,
  type RegisterPayload,
  type LoginResult,
  type VerifyEmailPayload,
  type PasswordResetRequestPayload,
  type PasswordResetRequestResult,
  type PasswordResetConfirmPayload,
  type MonitorSummary,
  type TradingAccountsAggregate,
  type BacktestStatistics,
  type RiskAlertStats,
  type RiskAlert,
  type SignalsDashboard,
  type TradingSignal,
  type HealthResult,
  type UserPreferences,
  type ChangePasswordResult,
  type DeleteAccountResult,
  type StrategyStatus,
  type StrategyTemplate,
  type StrategyItem,
  type StrategyListResult,
  type CreateStrategyPayload,
  type CreateStrategyFromTemplatePayload,
  type UpdateStrategyPayload,
  type ValidateExecutionPayload,
  type ValidateExecutionResult,
  type StrategyBacktest,
  type StrategyBacktestListResult,
  type StrategyBacktestStats,
  type CreateBacktestForStrategyPayload,
  type ResearchPerformanceTaskPayload,
  type ResearchOptimizationTaskPayload,
  type ResearchTaskResult,
  type ResearchResultsListing,
  type BacktestCompareResult,
  healthCheck,
  getMonitorSummary,
  getTradingAccountsAggregate,
  getBacktestStatistics,
  getRiskAlertStats,
  getRiskAlerts,
  acknowledgeRiskAlert,
  resolveRiskAlert,
  getSignalsDashboard,
  getSignals,
  searchSignals,
  getSignalsPending,
  processSignal,
  executeSignal,
  cancelSignal,
  login,
  register,
  logout,
  verifyEmail,
  resendVerification,
  requestPasswordReset,
  confirmPasswordReset,
  getMe,
  updateMe,
  changePassword,
  deleteAccount,
  getPreferences,
  patchPreferences,
  getStrategyTemplates,
  getStrategies,
  getStrategy,
  createStrategy,
  createStrategyFromTemplate,
  updateStrategy,
  deleteStrategy,
  activateStrategy,
  deactivateStrategy,
  archiveStrategy,
  validateExecution,
  getStrategyBacktests,
  getStrategyBacktestStats,
  createBacktestForStrategy,
  submitResearchPerformanceTask,
  submitResearchOptimizationTask,
  getResearchResults,
  compareBacktests,
} from './endpoints'

// React hooks
export { AuthProvider, useAuth, type AuthState } from './hooks'
